abbreviations:
  languages:
    :ru: :russian
    :r:  :russian
    :en: :english
    :e:  :english
    :ua: :ukrainian
    :u:  :ukrainian
    :es: :spanish
    :de: :german
    :fr: :french
    :it: :italian
  services:
    :g: :google
    :m: :meta
    :b: :babelfish
    :p: :pereklad
    :t: :prompt

# полный список: af, sq, ar, be, bg, ca, zh-CN, zh-TW, hr, cs, da, nl, en, et, tl, fi, fr, gl, de, el, ht, iw, hi, hu, is, id, ga, it, ja, ko, lv, lt, mk, ms, mt, no, fa, pl, pt, ro, ru, sr, sk, sl, es, sw, sv, th, tr, uk, vi, cy, yi
google_languages: &google_languages
  :russian: ru
  :english: en
  :spanish: es
  :ukrainian: uk
  :german: de
  :french: fr
  :italian: it

pereklad_languages: &pereklad_languages
  :russian: Rus
  :english: Eng
  :spanish: es
  :ukrainian: Ukr
  :german: Ger
  :french: Fre
  :italian: it

:google:
  url: 'http://translate.google.com'
  input:
    form:
      selector: {:name: 'text_form'}
      from:
        field:
          selector: {:name: 'sl'}
        languages:
          <<: *google_languages
      to:
        field:
          selector: {:name: 'tl'}
        languages: 
          <<: *google_languages
      text:
        selector: {:name: 'text'}
  output:
    form:
      selector: {:action: '/translate_suggestion'}
      text:
        selector: {:name: 'gtrans'}

:babelfish:
  url: 'http://babelfish.yahoo.com/'
  input:
    form:
      selector: {:name: 'frmTrText'}
      directions:
        field:
          selector: {:name: 'lp'}
        directions:
          :'english-dutch': en_nl
          :'english-french': en_fr
          :'english-german': en_de
          :'english-greek': en_el
          :'english-italian': en_it
          :'english-japanese': en_ja
          :'english-korean': en_ko
          :'english-portuguese': en_pt
          :'english-russian': en_ru
          :'english-spanish': en_es
          :'dutch-english': nl_en
          :'dutch-french': nl_fr
          :'french-dutch': fr_nl
          :'french-english': fr_en
          :'french-german': fr_de
          :'french-greek': fr_el
          :'french-italian': fr_it
          :'french-portuguese': fr_pt
          :'french-spanish': fr_es
          :'german-english': de_en
          :'german-french': de_fr
          :'greek-english': el_en
          :'greek-french': el_fr
          :'italian-english': it_en
          :'italian-french': it_fr
          :'japanese-english': ja_en
          :'korean-english': ko_en
          :'portuguese-english': pt_en
          :'portuguese-french': pt_fr
          :'russian-english': ru_en
          :'spanish-english': es_en
          :'spanish-french': es_fr
      text:
        selector: {:name: 'trtext'}
  output:
    xpath: '//div[@id="result"]/div/text()'

:pereklad:
  url: 'http://pereklad.online.ua'
  input:
    form:
      selector: {:name: 'transl'}
      from:
        field:
          selector: {:name: 'TranFrom'}
        languages:
          <<: *pereklad_languages
      to:
        field:
          selector: {:name: 'TranTo'}
        languages: 
          <<: *pereklad_languages
      text:
        selector: {:name: 'SrcTxt'}
  output:
    form:
      selector: {:name: 'transl'}
      text:
        selector: {:name: 'DstTxt'}

:meta:
  url: 'http://translate.meta.ua'
  input:
    form:
      selector: {:name: 'form1'}
      directions:
        field:
          selector: {:name: 'language'}
        directions:
          :'russian-english': Rus-Eng
          :'english-russian': Eng-Rus
          :'ukrainian-english': Ukr-Eng
          :'english-ukrainian': Eng-Ukr
          :'russian-ukrainian': Rus-Ukr
          :'ukrainian-russian': Ukr-Rus
          :'russian-german': Rus-Ger
          :'german-russian': Ger-Rus
          :'ukrainian-german': Ukr-Ger
          :'german-ukrainian': Ger-Ukr
          :'english-german': Eng-Ger
          :'german-english': Ger-Eng
          :'russian-latvian': Rus-Lat
          :'latvian-russian': Lat-Rus
          :'ukrainian-latvian': Ukr-Lat
          :'latvian-ukrainian': Lat-Ukr
          :'english-latvian': Eng-Lat
          :'latvian-english': Lat-Eng
          :'german-latvian': Ger-Lat
          :'latvian-german': Lat-Ger
      text:
        selector: {:name: 'SrcTxt'}
  output:
    form:
      selector: {:name: 'form1'}
      text:
        selector: {:name: 'DstTxt'}

:prompt:
  url: 'http://online.perevodov.net/Perevodov.net/online-dictionaries/promt.php4'
  input:
    form:
      selector: {:name: 'trans'}
      directions:
        field:
          selector: {:name: 'direction'}
        directions:
          :'russian-english': re
          :'english-russian': er
      text:
        selector: {:name: 'source'}
  output:
    form:
      selector: {:name: 'trans'}
      text:
        selector: {:name: 'result'}

